### ISSUE TITLE
Must start in the A area

### ISSUE THREAD

**Issue by GitMensch** [vorfol/vms-ide#9]
![sample](https://user-images.githubusercontent.com/6699539/113735817-e1d9bb80-96fc-11eb-8efa-31cf490f7a3e.png)

As seen in the detailed error message the column is actual 8. Isn't that Area A's start?

```json
{
	"resource": "/x:/VMS/test.cob",
	"owner": "vms-cobol",
	"severity": 8,
	"message": "Must start in the A area",
	"startLineNumber": 1,
	"startColumn": 8,
	"endLineNumber": 1,
	"endColumn": 22
}
```

**Comment by vorfol** [comment]
see the issue #8

**Comment by GitMensch** [comment]
I see, the issue is the terminal format. I'm closing this issue in favor of #8 and will adjust that to a FR.
